try {
  const arr = [1, 2, 3, 4];
  for (let i = 0; i <= 4; i++) {
    console.log(arr[i]);
  }
} catch (e) {
  console.log("Out of bounds");
}
